services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Consumer\AccountsStreamingConsumer:
      tags:
        - { name: 'enqueue.topic_subscriber', client: 'data_streaming' }
