services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Consumer\AccountsStreamingConsumer:
      tags:
        - { name: 'enqueue.topic_subscriber', client: 'accounts' }

    App\Application\Service\AddNewTaskService:
      arguments:
        $producer: '@enqueue.client.tasks.producer'
