security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
              - App\Auth\Authenticator

    role_hierarchy:
      ROLE_MANAGER: ROLE_USER
      ROLE_ACCOUNTANT: ROLE_MANAGER
      ROLE_ADMIN: [ROLE_MANAGER, ROLE_ACCOUNTANT]

    access_control:
      - { path: '^/login/callback', roles: PUBLIC_ACCESS }
      - { path: '^/login', roles: PUBLIC_ACCESS }
      - { path: '^/', roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
