enqueue:
  accounts:
    transport:
      dsn: '%env(resolve:ENQUEUE_DSN)%'
      global:
        metadata.broker.list: '%env(resolve:KAFKA_BROKER_LIST)%'
    client:
      prefix: events
      app_name: auth
      router_topic: account
      router_queue: account
      default_queue: account
