enqueue:
  accounts_streaming:
    transport:
      dsn: '%env(resolve:ENQUEUE_DSN)%'
      global:
        metadata.broker.list: '%env(resolve:KAFKA_BROKER_LIST)%'
    client:
      prefix: stream
      app_name: auth
      router_topic: accounts
      router_queue: accounts
      default_queue: accounts
