security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        api_token:
          pattern: ^/token$
          security: false

        api:
          pattern: ^/api
          security: true
          stateless: true
          oauth2: true

        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
              login_path: app_login
              check_path: app_login
              enable_csrf: true
              default_target_path: app_index
              use_referer: true
            logout:
              path: app_logout
              target: app_index

    role_hierarchy:
      ROLE_USER: [ROLE_EMAIL, ROLE_PROFILE]
      ROLE_MANAGER: ROLE_USER
      ROLE_ACCOUNTANT: ROLE_MANAGER
      ROLE_ADMIN: [ROLE_MANAGER, ROLE_ACCOUNTANT]

    access_control:
      - { path: ^/register, roles: PUBLIC_ACCESS }
      - { path: ^/authorize, roles: PUBLIC_ACCESS }
      - { path: ^/login, role: PUBLIC_ACCESS }
      - { path: ^/token, role: PUBLIC_ACCESS }
      - { path: ^/.well-known, roles: PUBLIC_ACCESS }
      - { path: ^/api/user, role: ROLE_OAUTH2_EMAIL }
#      - { path: ^/, role: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
