security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_token:
          pattern: ^/token$
          security: false

        api:
          pattern: ^/api
          security: true
          stateless: true
          oauth2: true

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

    role_hierarchy:
      ROLE_MANAGER: ROLE_USER
      ROLE_ACCOUNTANT: ROLE_MANAGER
      ROLE_ADMIN: [ROLE_MANAGER, ROLE_ACCOUNTANT]

    access_control:
      - { path: '^/authorize', roles: PUBLIC_ACCESS }
      - { path: '^/login', roles: PUBLIC_ACCESS }
      - { path: '^/register', roles: PUBLIC_ACCESS }
      - { path: '^/token', roles: PUBLIC_ACCESS }
      - { path: '^/api/user', roles: ROLE_OAUTH2_PROFILE }
      - { path: '^/', roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
