version: "3.9"

services:
  auth:
    image:  caddy:2.7.6-alpine
    restart: on-failure
    container_name: "auth"
    volumes:
      - "./auth/docker/caddy/conf/Caddyfile:/etc/caddy/Caddyfile:ro,Z"
      - "./auth:/app:ro,Z"
      - "auth-data:/data:rw"
    ports:
      - "8080:80"
    networks:
      - internet
      - no-internet
    depends_on:
      - auth-php-fpm
  auth-php-fpm:
    restart: always
    image: "auth-php-fpm"
    container_name: "auth-php-fpm"
    build:
      context: "./auth/docker"
      dockerfile: php-fpm/Dockerfile
    volumes:
      - "./auth:/app:rw,Z"
    depends_on:
      - auth-db
    networks:
      - internet
      - no-internet
  auth-db:
    restart: always
    container_name: "auth-db"
    image: postgres:16.2-alpine
    volumes:
      - "auth-db-data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - internet
      - no-internet

  tasks:
    image:  caddy:2.7.6-alpine
    restart: on-failure
    container_name: "tasks"
    volumes:
      - "./tasks/docker/caddy/conf/Caddyfile:/etc/caddy/Caddyfile:ro,Z"
      - "./tasks:/app:ro,Z"
      - "tasks-data:/data:rw"
    ports:
      - "8081:80"
    networks:
      - no-internet
      - internet
    depends_on:
      - tasks-php-fpm
  tasks-php-fpm:
    restart: always
    image: "tasks-php-fpm"
    container_name: "tasks-php-fpm"
    build:
      context: "./tasks/docker"
      dockerfile: php-fpm/Dockerfile
    volumes:
      - "./tasks:/app:rw,Z"
    depends_on:
      - tasks-db
    networks:
      - internet
      - no-internet
  tasks-db:
    restart: always
    container_name: "tasks-db"
    image: postgres:16.2-alpine
    volumes:
      - "tasks-db-data:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - internet
      - no-internet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - no-internet
  broker:
    image: confluentinc/cp-server:7.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - no-internet

volumes:
  auth-db-data:
  tasks-db-data:
  auth-data:
  tasks-data:

networks:
  no-internet:
    internal: true
  internet:
    internal: false
