parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    League\Bundle\OAuth2ServerBundle\Entity\AccessToken:
      class: App\Entity\AccessToken

    League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface:
      class: App\Repository\AccessTokenRepository
      decorates: 'League\Bundle\OAuth2ServerBundle\Repository\AccessTokenRepository'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
