services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Consumer\AccountsStreamingConsumer:
      tags:
        - { name: 'enqueue.topic_subscriber', client: 'accounts' }

    App\Consumer\TaskStreamingConsumer:
      tags:
        - { name: 'enqueue.topic_subscriber', client: 'tasks' }

    App\Consumer\TaskLifecycleConsumer:
      tags:
        - { name: 'enqueue.topic_subscriber', client: 'tasks' }

    App\Application\Service\HandleTaskDataService:
      arguments:
        $producer: '@enqueue.client.billing.producer'

    App\Application\Service\TransactionApplyService:
      arguments:
        $producer: '@enqueue.client.billing.producer'

    App\Console\ProcessPaymentsCommand:
      arguments:
        $producer: '@enqueue.client.billing.producer'
