## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    exposedByDefault: false

entryPoints:
  http:
    address: :80

# API and dashboard configuration
api:
  insecure: true

# Access logs configuration
accessLog:
  filePath: "/var/log/traefik/error.log"
  format: "json"
  filters:
    statusCodes:
      - "404"
